// USER_LEVEL
export const ADD_USER_LEVEL = 'ADD_USER_LEVEL';
export const UPDATE_USER_LEVEL = 'UPDATE_USER_LEVEL';
export const DELETE_USER_LEVEL = 'DELETE_USER_LEVEL';
export const FETCH_USER_LEVELS_REQUEST = 'FETCH_USER_LEVELS_REQUEST';
export const FETCH_USER_LEVELS_SUCCESS = 'FETCH_USER_LEVELS_SUCCESS';
export const FETCH_USER_LEVELS_FAILURE = 'FETCH_USER_LEVELS_FAILURE';
export const FETCH_USER_LEVELS = 'FETCH_USER_LEVELS';
